### ISSUE TITLE
CLI should stop early when a step didn't succeed

### ISSUE THREAD

**Issue by mitschabaude** [o1-labs/zkapp-cli#154]
I'm getting output like
```bash
> npx zk deploy berkeley
✔ Build project
✔ Generate build.json
✔ Choose smart contract
  The 'Add' smart contract will be used
  for this network as specified in config.json.
✖ Generate verification key
  Error: Cannot call class constructor because snarkyjs has not finished loading.
Try calling `await isReady` before `new Bool()`
✖ Build transaction
  TypeError: smartContractDeploy is not a function
? Set transaction fee to deploy (in MINA): ‣  
```

It's annoying to be asked for a transaction fee when you already see that the earlier steps didn't succeed and deploying won't work.
At least in this particular case, the experience would be much better if the CLI stopped after `Generate verification key`

**Comment by mitschabaude** [comment]
It gets especially unnerving when the CLI asks you to "Confirm to send transaction" after 3 failed steps

**Comment by jasongitmail** [comment]
Weird. Yeah, good catch
