### ISSUE TITLE
List example projects and let user select them in the CLI

### ISSUE THREAD

**Issue by ymekuria** [o1-labs/zkapp-cli#168]
I propose to list the example projects and allow a user to select them directly in the CLI. Typing the command zk example will show a list of example projects in the CLI the the user can select. The command  zk example [name] will remain the same.

**Comment by jasongitmail** [comment]
+1 thanks for tracking this

**Comment by jasongitmail** [comment]
Reviewing with Yoni. We'd like to define this issue as a dropdown list that we define & update manually, rather than an HTTP request to Github which involves latency.
