### ISSUE TITLE
Add more robust validation to the deploy URL user input on config step

### ISSUE THREAD

**Issue by ymekuria** [o1-labs/zkapp-cli#170]
Currently the only validation is if the URL is not an empty string. The scope and types of validation are up for discussion. Validation ideas:

-URL validation
-minimum length validation
-http validation?(maybe some people won't want this)

**Comment by bkase** [comment]
TODO: Needs a spec before community task

**Comment by jasongitmail** [comment]
Reviewing with Yoni. We're aligned to close this because doesn't seem necessary
