### ISSUE TITLE
Fix unwanted caching of project template

### ISSUE THREAD

**Issue by MartinMinkov** [o1-labs/zkapp-cli#176]
**Description**
If you have the `zkApp-cli` installed, the cli will cache some of the Github assets that it uses. This causes issues because if we update these assets (like the project template), they will not change. The fix for this is to remove the `.gittar` directory created when using the `zkApp-cli`

**Comment by bkase** [comment]
We need a way to run a post-install step that runs after update, but NPM doesn't allow it.

Idea from @mitschabaude : Always try to pull the template, if no internet, give up.
