### ISSUE TITLE
Add support for mainnet 

### ISSUE THREAD

**Issue by shimkiv** [o1-labs/zkapp-cli#189]
We need a way (`zk config` step, perhaps) to configure the network type which will be used by CLI in order to interact with the SCs.
The issue right now is that it is impossible to deploy SC using latest `zkApp-CLI` against the network, binaries of which were built using `mainnet` `DUNE` profile.
* [Logs](https://app.zenhub.com/files/383602159/0bd6b67a-e0a8-4470-9e66-4add50e1b06b/download)

**Comment by mitschabaude** [comment]
(side note: it might be useful to have the "mainnet" option before actual mainnet, to enable e2e tests like the ones by @shimkiv)

**Comment by shimkiv** [comment]
https://github.com/o1-labs/o1js/pull/1387
