### ISSUE TITLE
Fix manual hack to increment nonce when deploying a zkApp

### ISSUE THREAD

**Issue by MartinMinkov** [o1-labs/zkapp-cli#196]
This issue is related to this line here:
https://github.com/o1-labs/zkapp-cli/blob/4bfd2803b5742e2da1fccc8b6ec8bc11359faef1/src/lib/deploy.js#L310

To discuss:
Is there a better way we should be incrementing nonce values when deploying zkApps?

**Comment by ymekuria** [comment]
This has been resolved
