### ISSUE TITLE
Update the template package.json entry point to reflect new naming convention

### ISSUE THREAD

**Issue by ymekuria** [o1-labs/zkapp-cli#212]

**Comment by jasongitmail** [comment]
Good catch. 
Should we remove [`main` and `type` properties](https://github.com/o1-labs/zkapp-cli/blob/main/templates/project-ts/package.json#L14) given projects won't have predictably named file for these? Will lack of one or both of these cause NPM, ESLint, or the NPM package publishing workflow to complain?

**Comment by mitschabaude** [comment]
@jasongitmail I think as it stands, it will probably work without `main`, but the `SmartContract` will only be importable from `"project-name/src/Add"`. Which is not a great default. Not sure about the types.

I think this issue also demonstrates that our naming convention is bad. `index.ts` shouldn't be a script that's unrelated to the project's exports. Instead, we could make index.ts the actual entry-point, either by putting the smart contract there or by importing it there. The script should be called something else, like `main.ts`.

**Comment by jasongitmail** [comment]
Yeah, supporting installation of a smart contract via NPM leads us the the right answer.

Projects can contain more than one smart contract, so the file mentioned shouldn't contain any smart contract logic itself, but just import & export all smart contract classes that the dev wants to access.
Do you agree @mitschabaude ?

Then we should debate the naming. How about trying `index.ts` for this file that we're discussing b/c it feels intuitive and something like `run.ts` for the script currently within each example that runs it locally? 

CC @bkase

**Comment by ymekuria** [comment]
I agree we need to change the convenctions to properly support the publishing and installing smart contracts via NPM. I agree with @jasongitmail and @mitschabaude that index.ts should be the entry point to the contract/contracts. The naming is up for debate. I think run.ts as a little more clear than script.ts.

**Comment by mitschabaude** [comment]
> the file mentioned shouldn't contain any smart contract logic itself, but just import & export all smart contract classes that the dev wants to access.
Do you agree @mitschabaude ?

Agreed!

For the script file, my preference list is `main.ts` > `run.ts` > `script.ts`

**Comment by jasongitmail** [comment]
Seems like we all kinda like `run.ts`. Let's give it a try! It's low commitment, easy to change.
