### ISSUE TITLE
RFC Proposal for simplifying how smart contracts are found in a project

### ISSUE THREAD

**Issue by jasongitmail** [o1-labs/zkapp-cli#232]
### Background

When we wrote the CLI initially, we hadn't yet required developers to import & export their smart contracts within `index.ts`. We added this to allow use of smart contracts that are published to NPM because it's necessary to expose the classes in a common manner.

Because of this, we searched the project to find any class extending `SmartContract` during deployment. This is easy for developers, but also left one edge case that we need to handle, which is dealing with 2+ smart contract having the same name.

### Proposal

During deployment, instead of generating a `build.json` and using `findSmartContracts()`, we could instead import the developer's `index.ts`, stringify class names that it exports, and look at these as the list of available smart contracts that can be deployed. This would enforce uniqueness of all class names and encourage developers to use our newer pattern of importing & exporting smart contracts within their `index.ts` because doing so would become a requirement for deployment as well.

(If making this change, we can also close [this related issue](https://github.com/o1-labs/zkapp-cli/issues/231) about warning if the same contract appears 2+ in the same project.)

**Comment by jasongitmail** [comment]
CC @ymekuria wdyt?

**Comment by ymekuria** [comment]
> and encourage developers to use our newer pattern of importing & exporting smart contracts within their `index.ts` because doing so would become a requirement for deployment as well.

I think this approach will work well @jasongitmail. If we go this route, we probably need to give users more guidance on import export pattern for `index.ts`. Currently, a user might only start thinking about this pattern when they are ready to integrate a contract into a UI. They will likely use the CLI to deploy before that point.

**Comment by mitschabaude** [comment]
+1 @jasongitmail, this approach seems cleaner / more explicit, I like how it naturally enforces uniqueness.

There are two ways we could obtain the class name string:
* either we use the string under which the class is exported, i.e. the one from `Object.keys(await import('index.js'))`
* or we use `Class.name` which is the name under which the class is _declared_

These two will only differ in edge cases, say when the developer exports it with something like `export {MyContract as MyContractRenamed}`. But strictly speaking, only the first of the two ensures uniqueness of the name, and feels more precise to me

**Comment by mitschabaude** [comment]
Something that came up when @carterbrett tried to deploy a zkapp -- error messages should be updated to guide the user to export their smart contract from `index.ts`.
Made an issue here: https://github.com/o1-labs/zkapp-cli/issues/234
I think ensuring a good error message can be part of this RFC's implementation

**Comment by jasongitmail** [comment]
Agreed. That's in scope here
