### ISSUE TITLE
Convert to ES6 imports

### ISSUE THREAD

**Issue by jasongitmail** [o1-labs/zkapp-cli#24]
Yargs failed with ES6 imports initially. Try again to see if it has fixed [the issue](https://github.com/yargs/yargs/issues/1844).

- [x] Convert to ES6 (note: project templates already use ES6 since they're unaffected by yargs)
- [x] run `npm remove eslint-plugin-import`
- [x] remove `"commonjs": true,` from snapp-cli's `.eslintrc` config.

**Comment by ymekuria** [comment]
Completed as a part of #447
