### ISSUE TITLE
Verify that sudoku1 example can be deployed

### ISSUE THREAD

**Issue by bkase** [o1-labs/zkapp-cli#254]
A user on discord is saying that there is an "error: at least one choice must be selectable" when trying to `zk deploy` this example

**Comment by mitschabaude** [comment]
maybe their config.json is in some way? or they don't have their smart contract exported, so it doesn't show up there?

**Comment by shimkiv** [comment]
Another (or similar) case was [reported[(https://discord.com/channels/484437221055922177/915745847692636181/1024429884547805254) which most likely cased by periodic GraphQL endpoint unavailability.

**Comment by mitschabaude** [comment]
This issue is likely not about graphql unavailability, because the error here happens in an earlier step
