### ISSUE TITLE
Set up CI to run test for multiple platforms, if possible (Linux, Windows, Mac)

### ISSUE THREAD

**Issue by jasongitmail** [o1-labs/zkapp-cli#257]
I.e. add Windows, because Linux and Mac have similar file path handling, but [Windows does not](https://github.com/o1-labs/zkapp-cli/pull/256).

**Comment by jasongitmail** [comment]
To research if this is an option on Github Actions

**Comment by ymekuria** [comment]
Completed as part of #447
