### ISSUE TITLE
`zk example` fails

### ISSUE THREAD

**Issue by mrmr1993** [o1-labs/zkapp-cli#261]
```
$ zk --version
0.4.16
```
```
$ zk example example_snarkyjs_project
✔ Fetch project template
✖ Extract example
Example not found
```

**Comment by jasongitmail** [comment]
@mrmr1993 If a directory of the same name already exists, it will not be clobbered  https://github.com/o1-labs/zkapp-cli/blob/main/src/lib/project.js#L24-L27 

We'll implement a dropdown of examples (sudoku & tictactoe currently) and constraint choices if specified as a parameter,  to avoid this issue. We just haven't gotten to it. I'll create an issue to track it.

**Comment by jasongitmail** [comment]
Example names will be now constrained when this [PR](https://github.com/o1-labs/zkapp-cli/pull/263) is merged. We will have this open PR for listing examples, as well, when the `name` parameter is not specified.
