### ISSUE TITLE
Add dropdown for example names and constraint paramter names allowed

### ISSUE THREAD

**Issue by jasongitmail** [o1-labs/zkapp-cli#262]
Dropdown if `zk example` is used. Constrain parameters if `zk example <name>` is used. (The latter can be done with yargs' "[choices](https://yargs.js.org/docs/#api-reference-choiceskey-choices)"). The former can be implemented similar to how we do it with teh `zk deploy` command currently (see that code).

**Comment by ymekuria** [comment]
We also have this similar issue for this #168

**Comment by jasongitmail** [comment]
Thanks. I just fixed the 2nd part on this [PR](https://github.com/o1-labs/zkapp-cli/pull/263). Let's close this issue and keep open the one you linked.
