### ISSUE TITLE
Auto import smart contract into the main page of the generated UI(?)

### ISSUE THREAD

**Issue by jasongitmail** [o1-labs/zkapp-cli#268]
This needs exploration to determine the best approach, for the user from dev to production. Likely just importing the file directly will work, both 1.) locally during dev, and 2.) will be built into their UI project. 

For our supported UI frameworks:
- [x] Svelte Kit
- [x] NextJS
- [x] VueJS

**Comment by ymekuria** [comment]
Closed 
#291 
#296
#295
