### ISSUE TITLE
Error when importing a smart contract into a nextjs ui from the contract directory file path

### ISSUE THREAD

**Issue by ymekuria** [o1-labs/zkapp-cli#280]
**Describe the problem**
An error occurs after creating a project using zk project <name> --ui next and importing the smart contract into the ui from the contract directory file path and also via npm link. 

ui/pages/index.js
```
import { Add } from "../../contracts/build/src/Add.js";

import { Mina, isReady } from 'snarkyjs'
```
Error message

```
Error: ENOENT: no such file or directory, open '/Desktop/gits/zkapp/ui/.next/server/pages/plonk_wasm_bg.wasm'
```
Everything works as expected when a smart contract is imported from a published npm package. 

Describe the proposed solution
No response

**Alternatives considered**
No response

**Importance**
High

**Additional Information**
No response

**Comment by bkase** [comment]
Look for relative imports of wasm

**Comment by bkase** [comment]
Look into custom import paths (or npm workspaces?) -- package field in packages.json?
