### ISSUE TITLE
Add SnarkyJS to UI scaffold project dependencies 

### ISSUE THREAD

**Issue by ymekuria** [o1-labs/zkapp-cli#284]
### Describe the problem

Currently users would need to npm install SnarkyJS in the UI project.

### Describe the proposed solution

This would eliminate the `npm install snarkyjs `step for users.

### Importance

nice to have

**Comment by jasongitmail** [comment]
PR: https://github.com/o1-labs/zkapp-cli/pull/286

**Comment by ymekuria** [comment]
PR: #286 closed this.
