### ISSUE TITLE
UI scaffold: Outline homepage design to provide user education and links to relevant docs

### ISSUE THREAD

**Issue by ymekuria** [o1-labs/zkapp-cli#289]
### Describe the problem

Users may need more guidance on next steps after generating a zkapp project with a ui.

### Describe the proposed solution

Create landing pages for all the supporting frameworks with user education and links to relevant documentation for next steps. 

### Importance

nice to have

**Comment by jasongitmail** [comment]
+1 great idea

Next step is an outline and then we can get a design for it

**Comment by nicc** [comment]
Indirectly Irresponsible Individual: @Trivo25
