### ISSUE TITLE
Run tests for examples (e.g. sudoku, tictactoe) as part of CI

### ISSUE THREAD

**Issue by bkase** [o1-labs/zkapp-cli#313]
See #311 

Every release we seem to break associated examples / tutorials. I think this is starting to be unsustainable.

**Comment by shimkiv** [comment]
Can be done as part of this [example](https://github.com/o1-labs/e2e-tests/blob/develop/tests/cli/zkapp-cli/zkAppCli.spec.ts). Wdyt?

**Comment by shimkiv** [comment]
Also related: 
- https://github.com/o1-labs/e2e-tests/issues/21
- https://github.com/o1-labs/e2e-tests/issues/22

**Comment by mitschabaude** [comment]
I think ideal would be in zkapp-cli's CI, whenever you bump the snarkyjs version (because that indicates examples getting out of date)

**Comment by shimkiv** [comment]
```shell
yarn test --grep @zkapp-cli
```
(I believe that other repos can be checked out in CI, isn't it?)

**Comment by ymekuria** [comment]
> I think ideal would be in zkapp-cli's CI, whenever you bump the snarkyjs version (because that indicates examples getting out of date)

+ 1 on this

**Comment by bkase** [comment]
Potentially will be handled by a grant!

**Comment by jasongitmail** [comment]
Running the unit tests would be very simple and can be added here https://github.com/o1-labs/zkapp-cli/blob/main/.github/workflows/ci.yml#L24
