### ISSUE TITLE
Fix jest resolver config

### ISSUE THREAD

**Issue by mitschabaude** [o1-labs/zkapp-cli#317]
by @gretzke 

Adaption necessary in `jest.resolver.config` to avoid `SyntaxError: Unexpected token 'export'`
```js
transformIgnorePatterns: [
  '<rootDir>/node_modules/(?!snarkyjs/node_modules/tslib)', => 'node_modules/(?!tslib)'
]
```

**Comment by ymekuria** [comment]
Completed in this PR https://github.com/o1-labs/zkapp-cli/pull/376
