### ISSUE TITLE
[Discussion] Consider splitting src and test into separate folders, using TS references

### ISSUE THREAD

**Issue by dillongrove** [o1-labs/zkapp-cli#32]
See: https://www.typescriptlang.org/docs/handbook/project-references.html

The first few paragraphs of the above explain pretty well why this might be a good idea. Depends a bit on how large we see these projects getting though, as this could be overkill.

**Comment by jasongitmail** [comment]
Closing to clean up. Reviewed with Yoni. It would how we do create examples using the CLI, which currently replaces the entirely `src` directory. So cost outweight any preference/benefit here.
