### ISSUE TITLE
0.5.3 can't deploy snarkyjs 0.7.3 mina tutorial contracts

### ISSUE THREAD

**Issue by iam-robi** [o1-labs/zkapp-cli#323]
### Describe the bug

Starting from tutorials https://docs.minaprotocol.com/zkapps/tutorials/oracle the command zk deploy fails after updating the example contract  s with snarky 0.7.3 and the cli to 0.5.3 the error returned is: 
```
  Error: addMissingSignatures: Cannot add signature for B62..., private key is missing.
 ```

if removing the this.requireSignature() in the init function the error returned is : 

```
  Failed to send transaction to relayer. Errors: Couldn't send zkApp command: (Verification_failed
 "Missing_verification_key: [B62...]")

```

I just cloned the following repo, which is referenced in tutorial article https://github.com/jackryanservia/oracle-example

Same behaviour occurs with tutorial 8. 
https://github.com/es92/zkApp-examples/blob/main/08-custom-tokens/src/BasicTokenContract.ts

The command `zk deploy` works well however after a project created with `zk project`. In this case the contract do not contain a "deploy" method. 

### Steps to Reproduce

1. clone https://github.com/jackryanservia/oracle-example
2. update snarkyjs to 0.7.3
3. run `zk config` and configure berkeley
4.  run `zk deploy berkeley`

### System Info

```shell
System:
    OS: macOS 12.4
    CPU: (10) arm64 Apple M1 Max
  Binaries:
    Node: 18.6.0 - ~/.asdf/installs/nodejs/18.6.0/bin/node
    Yarn: 1.22.19 - ~/.asdf/installs/nodejs/18.6.0/.npm/bin/yarn
    npm: 8.13.2 - ~/.asdf/plugins/nodejs/shims/npm
  npmPackages:
    snarkyjs: Not Found (not in a project)
  npmGlobalPackages:
    zkapp-cli: 0.5.3
```

### Severity

blocking all usage

**Comment by Trivo25** [comment]
Good catch. It seems like the zkApp CLI can't handle when a contract requires a signature on deployment (in the init method)

**Comment by jrwashburn** [comment]
> Good catch. It seems like the zkApp CLI can't handle when a contract requires a signature on deployment (in the init method)

I am reproducing this on other contracts - consistently fail zk deploy with "private key is missing".

I don't think it is related to the signature being required - I've tried reducing deploy all the way down to simply:

`
deploy() {
    super.deploy();
  }
`
Removing the deploy function altogether allows the zk deploy to complete.

**Comment by mitschabaude** [comment]
@jrwashburn do you also reproduce the for contracts where init() doesn't call requireSignature()? init() is called by super.deploy()

**Comment by mitschabaude** [comment]
Actually @jrwashburn that deploy function you show is not passing on the deployArgs down, which would explain the error I think

**Comment by mitschabaude** [comment]
So I think these are two independent ways of causing this error

**Comment by jasongitmail** [comment]
@mitschabaude do you know off hand if this should stay open or stale issue?

**Comment by mitschabaude** [comment]
@jasongitmail can be closed
