### ISSUE TITLE
Improve error handling when imported smart contract is not found

### ISSUE THREAD

**Issue by mitschabaude** [o1-labs/zkapp-cli#329]
When importing a smart contract throws an error, the CLI assumes that it "failed to find the smart contract in your build directory". It logs that error message to the user and exits.

https://github.com/o1-labs/zkapp-cli/blob/35f48b1755f3b35b06e0d164ea7d6449b9dcb44a/src/lib/deploy.js#L222-L228

However, there are many errors that can happen when importing a contract. Thererfore, it's a bad idea to swallow the error like that - it makes it extremely hard for users to find the real error. See https://github.com/o1-labs/zkapp-cli/issues/328 for example

Proposed solution is to specifically test whether we can find the contract file in the build directory, and log the existing error if we don't. After that, we just try to import the smart contract. If that fails, node will throw the proper error, which enables the user to identify the problem. If we want to print something pretty, or change the error color, we can achieve that with a `try .. catch`, but not at the cost of removing the stack trace / full error message.

**Comment by jasongitmail** [comment]
Discussed with Yoni during review. +1 for this

**Comment by xendarboh** [comment]
This can eat space time.  `console.log(_)`
