### ISSUE TITLE
[Discussion] Is it worth having a standalone `jest.config.ts` file?

### ISSUE THREAD

**Issue by dillongrove** [o1-labs/zkapp-cli#33]
See: https://jestjs.io/docs/configuration

This could also be done using a `jest` key in the `package.json`, but imo having a separate file is slightly cleaner. This isn't necessary if there isn't any configuration we want to change from the default, but from a quick perusal of the options it seems like there is some useful stuff.

**Comment by jasongitmail** [comment]
Yes I think so. +1 

There is a `jest.config.js` for `project-ts` so that it can run `.ts` extension test files. When updating the Snapp CLI to run both JS and TS tests, I think it'll likely be necessary to use the same `jest.config.js` as found in `project-ts`.

**Comment by jasongitmail** [comment]
Closing to clean up. This file exists now
