### ISSUE TITLE
Improve error message for `zk deploy` when fee payer has insufficient permissions

### ISSUE THREAD

**Issue by bkase** [o1-labs/zkapp-cli#331]
`zk deploy` hardcodes the zkapp private key as the fee payer for the transaction -- this is fine if you fund the account and deploy once, but by default the permission for sending tokens is Proof which means you can't use this account as the fee payer again easily (unless your smart contract is smart enough to send funds, but that's unlikely).

We should:

Show a better error message when this happens. Right now it's quite confusing. The error from the GraphQL response is: "Fee_payer_not_permitted_to_send". The new message should instruct the user that they need to use a different account as the fee payer

Also see https://github.com/o1-labs/zkapp-cli/issues/129

**Comment by jasongitmail** [comment]
#[2 is tracked here](https://github.com/o1-labs/zkapp-cli/issues/129). We could bump it up on priority, but previously haven't prioritized it during Testnet
