### ISSUE TITLE
Use version of 0.9.* in projects

### ISSUE THREAD

**Issue by jasongitmail** [o1-labs/zkapp-cli#374]
### Describe the problem

When SnarkyJS release bug fix updates, we have to bump it within the project within zkApp CLI too. It's a bit of a hassle. 

### Describe the proposed solution

Following semver, we could use version of `0.9.*` for SnarkyJS within the project template within the CLI, to avoid needing to update it for bug releases. However, we would still want to manually bump the major (during v1+) or minor (during v0) .

CON:
We would need to remove `package-lock.json`, which means project creation will be noticeably slower because NPM has to go through it's entire dep analysis process. 

PRO:
This is the version format we really want in projects, so the loss of project creation speed may be something worth swallowing. 

### Importance

nice to have

**Comment by ymekuria** [comment]
I like this idea! We need to verify that  running `zk system` will display the correct SnarkyJS version after implementing this.
