### ISSUE TITLE
SnarkyJS releases in Github

### ISSUE THREAD

**Issue by stevenpack** [o1-labs/zkapp-cli#407]

**Comment by stevenpack** [comment]
We don't have any releases here:
https://github.com/o1-labs/snarkyjs/releases

Instead we have tags:
https://github.com/o1-labs/snarkyjs/tags

But the tags don't say anything about the release. You have to go search for the changelog to find it.

Better practice is like this: https://github.com/thirdweb-dev/contracts/releases

Where you can see at a glance the changes in a release. I'd like to see us embrace this pattern.

**Comment by mitschabaude** [comment]
@stevenpack do you think we can just link to the correct heading inside the changelog from the releases page?

**Comment by stevenpack** [comment]
@mitschabaude what do you mean by the releases page? I mean this one: https://github.com/o1-labs/snarkyjs/releases

**Comment by mitschabaude** [comment]
> @mitschabaude what do you mean by the releases page? I mean this one: https://github.com/o1-labs/snarkyjs/releases

I meant the same one! But we could also copy the changelog changes over to releases I guess

**Comment by barriebyron** [comment]
The release process on Notion is a WIP https://www.notion.so/minaprotocol/zkApps-Release-cd61fe7e24574a1181923142113cff15 After we land on how we do releases, I can work to make an accurate artifact so we have a record of this workflow and decision

**Comment by barriebyron** [comment]
Unrelated to the release process itself, but let's also work to capture the deprecation cycle timeline in the release process

**Comment by ymekuria** [comment]
Completed in here and in https://github.com/o1-labs/o1js
