### ISSUE TITLE
make docs builds less brittle

### ISSUE THREAD

**Issue by barriebyron** [o1-labs/zkapp-cli#415]
local builds for the docs2 repo require Node.js version 16, precisely

If you require other node versions for other work and forget to switch back to node version 16, it's very frustrating when the local doc build fails

**Comment by barriebyron** [comment]
work done in https://github.com/o1-labs/docs2/pull/414

**Comment by ymekuria** [comment]
@barriebyron, could you clarify this issue regarding the `zkApp cli `?

**Comment by barriebyron** [comment]
> @barriebyron, could you clarify this issue regarding the `zkApp cli `?

@ymekuria  the PR provides a command that let's local doc builds work even when you have a later node version installed

https://github.com/o1-labs/docs2/pull/414/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R28 

It might not be related to zkApp CLI, but if it is, can you teach me how this doc readme update might impact zkApp CLI? 

and welcome back from vacation!
