### ISSUE TITLE
`zk deploy` not working on Windows

### ISSUE THREAD

**Issue by MartinMinkov** [o1-labs/zkapp-cli#418]
### Describe the bug

When calling `zk deploy`, windows machines seem to error. 

See this discord thread here: https://discord.com/channels/484437221055922177/1113467552312602746

### Steps to Reproduce

1. Create project
2. run `zk deploy`

### System Info

```shell
NA
```

### Severity

annoyance

**Comment by ymekuria** [comment]
This is potentially fixed with this PR https://github.com/o1-labs/snarkyjs-bindings/pull/19.
