### ISSUE TITLE
Improve `interact.ts`

### ISSUE THREAD

**Issue by shimkiv** [o1-labs/zkapp-cli#435]
### Describe the problem

- Use [`fee`](https://github.com/o1-labs/zkapp-cli/blob/f6fdcd24185bb31d9e370bc188d42b462d044a45/templates/project-ts/src/interact.ts#L52) from deployment configuration.
- We also should log the error within the [`else` block](https://github.com/o1-labs/zkapp-cli/blob/f6fdcd24185bb31d9e370bc188d42b462d044a45/templates/project-ts/src/interact.ts#L59).

### Describe the proposed solution

...

### Importance

would make my life easier

**Comment by ymekuria** [comment]
Completed with #424
