### ISSUE TITLE
"Beta" tag in documentation for keccak+ECDSA

### ISSUE THREAD

**Issue by stevenpack** [o1-labs/zkapp-cli#440]
Closed this issue (wrong repository) and created an issue in the docs2 repo for us

https://app.zenhub.com/workspaces/zkapps-product-eng-6130fedb3b0fc600123d8796/issues/gh/o1-labs/docs2/450

**Comment by ymekuria** [comment]
> The crypto team doesn't characterize ECDSA+keccak as "production hardened" yet, but we want to get into the hands of our users to get usability and performance feedback. We should make this clear in the docs. If we don't already have it, please introduce the concept of tagging a feature as "beta" and start with ECDSA. (or if we already have an existing lifecycle type of annotation, please use that).
> 
> cc @nicc @joseandro

@stevenpack I think you meant to add this issue to the docs repo https://github.com/o1-labs/docs2/issues .
