### ISSUE TITLE
Replicate GitHub README.md on npm page (currently blank)

### ISSUE THREAD

**Issue by stevenpack** [o1-labs/zkapp-cli#445]

**Comment by stevenpack** [comment]
Our project looks dead on NPM. Let's replicate the README content there.

![Screenshot 2023-06-29 at 5.37.33 PM.png](https://images.zenhubusercontent.com/642f2877fd180cc3c4d39d29/989efedf-9e4f-4798-8b54-2c7c4fac6d39)

**Comment by mitschabaude** [comment]
I think this is a problem of npm. I observed the same and checked some popular package which also didn't display the readme.

**Comment by barriebyron** [comment]
How unfortunate!
AFAIK, the contents of the project README create the npm landing page

Doing a little searching on npm, I discovered a rogue `snarkyjs-test` npm page, how do we remove https://www.npmjs.com/package/snarkyjs-test ? 

> 0.9.7 • Public • Published 3 months ago

After refreshing my browser pages, the official SnarkyJS npm page is correctlyu showing for me now on Brave, Chrome, and Safari
https://www.npmjs.com/package/snarkyjs

**Comment by barriebyron** [comment]
This issue was an npm bug... now automagically fixed
