### ISSUE TITLE
Fee-Payer Alias shows as undefined for zk deploy 

### ISSUE THREAD

**Issue by barriebyron** [o1-labs/zkapp-cli#446]
### Describe the bug

The Fee-Payer Alias incorrectly shows `undefined` in the confirm transaction step:
<img width="799" alt="image" src="https://github.com/o1-labs/zkapp-cli/assets/10067215/e81e114b-e044-485c-8689-266cda497e09">

The zk deploy command correctly created the fee payer key pair at /Users/<username>/.cache/zkapp-cli/keys/03-deploy.json (also at /Users/<username>/.cache/zkapp-cli/keys/03-deploy.json)

and the config.json shows it:

```
{
  "version": 1,
  "deployAliases": {
    "berkeley": {
      "url": "https://proxy.berkeley.minaexplorer.com/graphql",
      "keyPath": "keys/berkeley.json",
      "feepayerKeyPath": "/Users/barriebyron/.cache/zkapp-cli/keys/03deploy.json",
      "feepayerAlias": "03deploy",
      "fee": "0.1",
      "smartContract": "Square"
    }
  }
}
```

I haven't tested the other workflows yet, just the create a new fee payer key pair

### Steps to Reproduce

Follow the steps in tutorial 3 https://docs.minaprotocol.com/zkapps/tutorials/deploying-to-a-network to 

When prompted to choose an account to pay transaction feeds, select to **use a different account** then select to **create a new fee payer key pair** then give an alias to your new fee payer key pair (I tested with `03-deploy` and also `03deploy` 

### System Info

```shell
➜  03-deploying-to-a-live-network git:(main) ✗ zk system
Please include the following when submitting a Github issue:

  System:
    OS: macOS 13.4.1
    CPU: (12) arm64 Apple M2 Pro
  Binaries:
    Node: 18.5.0 - ~/.nvm/versions/node/v18.5.0/bin/node
    Yarn: Not Found
    npm: 8.12.1 - ~/.nvm/versions/node/v18.5.0/bin/npm
  npmPackages:
    snarkyjs: 0.11.3
  npmGlobalPackages:
    zkapp-cli: 0.10.0
```

### Severity

annoyance

**Comment by ymekuria** [comment]
@barriebyron try updating your cli version. The current version is `0.10.1`

**Comment by barriebyron** [comment]
@Yoni Mekuria ***@***.***>  what is the best way to update the
zkApp CLI?

**Comment by ymekuria** [comment]
@barriebyron the best way is to run `npm update -g zkapp-cli`.
