### ISSUE TITLE
Define core development workflow

### ISSUE THREAD

**Issue by nicc** [o1-labs/zkapp-cli#469]
We need a clear definition of what the developer feedback loop is so that we can publicise, measure and improve it.

**Comment by nicc** [comment]
Indirectly responsible individual: Nic / Gar

**Comment by ymekuria** [comment]
Current workflow



1. Install or update the zkapp-cli
	- npm install -g zkapp-cli
2. Create a Project
	- zk project <your-project-name>
		- Select none or the desired UI framework when prompted to generate an accompanying UI project.
3. Add Smart contract boiler plate
	- Note: Basic smart contract with boiler plate is included in the Add.ts file when a project is generated with the zkapp-cli
	- Import o1js 
		- https://github.com/o1-labs/zkapp-cli/blob/main/templates/project-ts/src/Add.ts#L1
	- Extend the Smart contract class 
		- https://github.com/o1-labs/zkapp-cli/blob/main/templates/project-ts/src/Add.ts#L12
4. Add testing boilerplate
	- Note: Tests and  boiler plate example are included in the [Add.test.ts](http://add.test.ts/) file when a project is generated with the zkapp-cli
	- Import smart contract and o1js into test file. 
		- https://github.com/o1-labs/zkapp-cli/blob/main/templates/project-ts/src/Add.test.ts#L1-L2
	- Create a local Blockchain instance to interact with 
		- https://github.com/o1-labs/zkapp-cli/blob/main/templates/project-ts/src/Add.test.ts#L27-L28
	- Initialize test accounts to pay fees and sign transactions. An array of 10 accounts are provided with o1js 
		- https://github.com/o1-labs/zkapp-cli/blob/main/templates/project-ts/src/Add.test.ts#L29-L31
	- Deploy the contract to the local blockchain
		- https://github.com/o1-labs/zkapp-cli/blob/main/templates/project-ts/src/Add.test.ts#L29-L31
5. Add an @method or other functionality to the smart contract.
	- Invoke the method that was added  or utilize new functionality in test file
		- https://github.com/o1-labs/zkapp-cli/blob/main/templates/project-ts/src/Add.test.ts#L57-L65
		- If it works as expected with no errors, repeat step 5 and add more functionality
		- If  there are errors, look through the  stacktrace( set to 1000 to sift through long trace of ocaml errors)  to find the source of the error and update the contract to resolve them.
6. Create an integration test
	- Create a nodejs script to run the smart contract and test it's functionality(similar to step 4). This path can be used instead of using jest with similar steps
		- Note: An example nodejs script that runs the Add smart contract included with the zkapp-cli  can be found in the [run.ts](http://add.test.ts/) file 
7. Test with a live network
	- Deploy the smart contract to the Berkeley Testnet
		- configure your zkapp 
			- zk config in the root of the smart contract project
				- Follow the command prompts to add a deploy alias
					- Note: option B step 5 on this page shows and example of adding a deploy alias https://docs.minaprotocol.com/zkapps/how-to-write-a-zkapp#option-b-start-your-own-project 
				- chose a fee payer alias
					- Note: option B step 5 on this page shows and example of adding a deploy alias https://docs.minaprotocol.com/zkapps/how-to-write-a-zkapp#option-b-start-your-own-project  
		- Create a script to interact with a live network
			- examples 
				- https://github.com/o1-labs/zkapp-cli/blob/main/templates/project-ts/src/interact.ts
				- https://github.com/o1-labs/o1js/blob/main/src/examples/zkapps/hello_world/run_live.ts
		- Repeat step 7 after new features are added to your contract to test with a live network

**Comment by ymekuria** [comment]
In the current workflow a zkapp can be tested using jest or by creating a nodejs script to interact with the smart contract. This can be confusing for new developers.
