### ISSUE TITLE
Node 20 support

### ISSUE THREAD

**Issue by shimkiv** [o1-labs/zkapp-cli#471]
Since Node 16 will be EOL soon we need to make sure app will continue work with Node 18 and 20 (including CI)

**Comment by shimkiv** [comment]
`Node 20` will complain on `--experimental-wasm-threads` usage: `node: bad option: --experimental-wasm-threads`.
[Example](https://github.com/o1-labs/zkapp-cli/blob/e98a12de3a2e9d63b7931a477baef82ae245696a/templates/project-ts/package.json#L22).

**Comment by shimkiv** [comment]
Is it safe to remove this option since it only needed for `Node 14`?

**Comment by mitschabaude** [comment]
yes let's remove it 👍🏻
