### ISSUE TITLE
Fix NPM CI publish job correctly on version 16

### ISSUE THREAD

**Issue by MartinMinkov** [o1-labs/zkapp-cli#50]

**Comment by jasongitmail** [comment]
Ideally, we update the "if" condition [here](https://github.com/o1-labs/snapp-cli/blob/main/.github/workflows/ci.yml#L32), to only run for the first NodeJS version listed in the matrix, if that's possible within Github Actions.

**Comment by jasongitmail** [comment]
I think we can close this. Lmk if it should be reopend @MartinMinkov
