### ISSUE TITLE
Use path.resolve with feePayerCacheDir

### ISSUE THREAD

**Issue by shimkiv** [o1-labs/zkapp-cli#513]
https://github.com/o1-labs/zkapp-cli/pull/510#discussion_r1376578922

**Comment by ymekuria** [comment]
Does the feePayerCacheDir not work correctly with Windows @shimkiv ? I thought we tested it.

**Comment by shimkiv** [comment]
It does yet at the same time it probably better to protect us should something change in deps or runtime in future.

**Comment by ymekuria** [comment]
Completed in #510
