### ISSUE TITLE
Rename deprecated assert* to require* in o1js precondition APIs

### ISSUE THREAD

**Issue by mitschabaude** [o1-labs/zkapp-cli#526]
adapt the CLI to https://github.com/o1-labs/o1js/issues/1247

**Comment by mitschabaude** [comment]
cc @LuffySama-Dev

**Comment by LuffySama-Dev** [comment]
> cc @LuffySama-Dev

Hi Gregor, 
Thanks for assigning.
I will get started with it 🙋.

Thank You 😄
