### ISSUE TITLE
Dockerization of Mina local networks - Mac Silicon is not supported by the Docker image

### ISSUE THREAD

**Issue by dfstio** [o1-labs/zkapp-cli#529]
The docker image on https://hub.docker.com/r/o1labs/mina-local-network does not support a Mac Silicon processor and throws an illegal instruction error when running on M2 Max.

**Comment by shimkiv** [comment]
Hey @dfstio, thanks for reporting this.
Can I ask you to try it again please on the Mac with Apple silicon? 
`zk lightnet start` should pull the latest image with possible fix.

**Comment by shimkiv** [comment]
It doesn't work. We need to cross-build images for Arm platform. Details in that Discord thread.

**Comment by shimkiv** [comment]
Good progress so far. We have a build-system for `arm64` now 🎉
