### ISSUE TITLE
Failed to detect the installed CLI version.

### ISSUE THREAD

**Issue by satyambnsal** [o1-labs/zkapp-cli#550]
### Describe the bug

Deploy account fails to detect installed `zkapp-cli` version in **getInstalledCliVersion** method if **NodeJS**.
This usually happens if NodeJS is installed by tools like [Volta](https://volta.sh/)

If that is the case, We get the following error
```
TypeError: Cannot read properties of undefined (reading '0')
    at hasBreakingChanges (file:///Users/satyam/.volta/tools/image/packages/zkapp-cli/lib/node_modules/zkapp-cli/src/lib/deploy.js:561:26)
```

### Steps to Reproduce

1. Install NodeJS with [Volta](https://volta.sh/) or something similar on your machine.
2. Install `zkapp-cli` using `npm install -g zkapp-cli`
3. Run `zk config` and then `zk deploy` command inside a zk project.

### System Info

```shell
System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M1
  Binaries:
    Node: 21.2.0 - ~/.volta/tools/image/node/21.2.0/bin/node
    Yarn: 1.22.18 - ~/.volta/tools/image/yarn/1.22.18/bin/yarn
    npm: 9.2.0 - ~/.volta/tools/image/npm/9.2.0/bin/npm
  npmPackages:
    o1js: 0.15.2
  npmGlobalPackages:
    zkapp-cli: Not Found
```

### Severity

annoyance

**Comment by ymekuria** [comment]
Closed with #551
