### ISSUE TITLE
Accounts-Manager to continue accounts fetching procedure in case if genesis ledger account entry does not provide the `sk` property.

### ISSUE THREAD

**Issue by shimkiv** [o1-labs/zkapp-cli#617]

**Comment by mitschabaude** [comment]
this has also been a source of test flakes in o1js CI

**Comment by shimkiv** [comment]
Fixed, building now for different arch and will rebuild lightnet images.

**Comment by shimkiv** [comment]
https://github.com/shimkiv/mina-accounts-manager/releases/tag/v0.1.1
Will be published to DockerHub after the https://github.com/o1-labs/mina-lightnet-docker/actions/runs/8660174646
