### ISSUE TITLE
Add memo field to the Mempool zkApp transactions form in the Lightweight Mina Explorer

### ISSUE THREAD

**Issue by dfstio** [o1-labs/zkapp-cli#626]
### Describe the problem

It is very convenient to see the type of transaction using the memo. However, it is not fully clear now from the Mempool zkApp transactions form in the Lightweight Mina Explorer what transaction is being processed as only addresses are shown.
<img width="707" alt="Screenshot 2024-04-23 at 17 20 26" src="https://github.com/o1-labs/zkapp-cli/assets/110384358/ad6c0a92-16fb-43af-b20f-6a033fa66101">

### Describe the proposed solution

Add the memo field. Examples of the other explorers:
https://minascan.io/devnet/account/B62qqNQ9kMtc4L9p19eK8SfLRy8EamtMRWAVqcCaJSM1Q5AD3DjNAME/txs?type=zk-acc
https://devnet.minaexplorer.com/wallet/B62qqNQ9kMtc4L9p19eK8SfLRy8EamtMRWAVqcCaJSM1Q5AD3DjNAME/zkapp-transactions

### Importance

nice to have

**Comment by shimkiv** [comment]
@dfstio thanks for the feature request.
It was done by https://github.com/o1-labs/mina-lightweight-explorer/commit/173bc16f9ccc26120cc0b9b159065fdbb1d7e916
You can now do `zk lightnet explorer` and it will fetch the latest (`v0.2.0`) version locally.

**Comment by dfstio** [comment]
¡Muchas gracias! It is working perfectly)
![Screenshot 2024-04-24 at 01 49 56](https://github.com/o1-labs/zkapp-cli/assets/110384358/822bee66-a052-4237-9b4e-1fc817accc3f)

**Comment by shimkiv** [comment]
Oops, I'll release v0.2.1 soon-ish to also remove null/control chars from the resulting decoded string.

**Comment by shimkiv** [comment]
Done, `v0.2.1` released so you can retry `zk lightnet explorer` to fetch it.
