### ISSUE TITLE
[Windows] `zk system` command does not report zkapp-cli version

### ISSUE THREAD

**Issue by jasongitmail** [o1-labs/zkapp-cli#66]
Martin's testing showed that envinfo's CLI reports it correctly:
```sh
npx envinfo --npmGlobalPackages

  npmGlobalPackages:
    zkapp-cli: 0.1.22
```

But when used programatically we get the following (even though it works on Mac & Linux):
```
  npmGlobalPackages:
    zkapp-cli: Not Found
```

Possibly due to an upstream bug in envinfo. Related:
- https://github.com/tabrindle/envinfo/issues/143 
- https://github.com/tabrindle/envinfo/pull/144

**Comment by jasongitmail** [comment]
@MartinMinkov Still an issue? We'll keep open if so. Can you check on Windows please

**Comment by shimkiv** [comment]
It seems still be the case on Windows (checked on 11 both CMD and PowerShell). Will take a look on the issue.

<img width="1203" alt="image" src="https://github.com/o1-labs/zkapp-cli/assets/4096154/873389cc-5cd1-4fac-9ba4-09e623800233">
