### ISSUE TITLE
TypeError while running the Next.js build

### ISSUE THREAD

**Issue by boray** [o1-labs/zkapp-cli#678]
### Describe the bug

Zkapp-cli generated next project builds but gives the error below while running the build.

![Screenshot 2024-07-02 at 14 36 22](https://github.com/o1-labs/zkapp-cli/assets/24796421/4d8d7ea1-8015-46f6-b951-39d7d72a86bb)

[discord](https://discord.com/channels/484437221055922177/1255336211908661339)

### Steps to Reproduce

```
$ zk project test
✔ Create an accompanying UI project too? · next
✔ Do you want to set up your project for deployment to GitHub Pages? · no
✔ Would you like to use TypeScript?  Yes
✔ Would you like to use ESLint?   Yes
✔ Would you like to use Tailwind CSS?  Yes

$ cd test/ui
$ npm run build
$ npm run start
```

### System Info

```shell
System:
    OS: macOS 14.4.1
    CPU: (8) arm64 Apple M2
  Binaries:
    Node: 18.17.0 - ~/.nvm/versions/node/v18.17.0/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v18.17.0/bin/yarn
    npm: 10.8.1 - ~/.nvm/versions/node/v18.17.0/bin/npm
  npmPackages:
    o1js: ^1.3.1 => 1.3.1 
  npmGlobalPackages:
    zkapp-cli: 0.21.5
```

### Severity

blocking all usage

**Comment by shimkiv** [comment]
Probably also is related to https://github.com/o1-labs/zkapp-cli/issues/663

**Comment by 45930** [comment]
@boray I am no longer reproduce this issue.  With zkapp-cli 0.21.5 and o1js version 1.6.0, building and starting an app works fine.  Can you confirm on your machine?

**Comment by boray** [comment]
I'm still getting the same error with zkapp-cli 0.21.5 and o1js 1.6.0.

**Comment by boray** [comment]
I am no longer able to reproduce the issue.
